[package]
name = "schwitzerflut-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive", "env"] }
image = "0.25.5"
schwitzerflut-protocol = { path = "../schwitzerflut-protocol" }
