name: "CI"

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Nix store
        uses: actions/cache@v3.3.1
        id: nix-cache
        with:
          path: /tmp/nixcache
          key: ${{ runner.os }}-${{ hashFiles('**/flake.lock', '**/flake.nix') }}

      - name: Set up QEMU binfmt for cross compiling
        uses: docker/setup-qemu-action@v3

      - name: Install Nix
        uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011 # v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Import Nix store cache
        if: "steps.nix-cache.outputs.cache-hit == 'true'"
        run: |
          nix-store --import < /tmp/nixcache

      - name: Set up binary cache
        uses: cachix/cachix-action@v12
        with:
          name: nix-rust-template
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Check flake
        run: nix flake check --accept-flake-config

      - name: Export Nix store cache
        if: "steps.nix-cache.outputs.cache-hit != 'true'"
        run: |
          nix-store --export $(find /nix/store -maxdepth 1 -name '*-*') > /tmp/nixcache

  build:
    runs-on: ubuntu-latest
    needs:
      - test

    strategy:
      matrix:
        system:
          - "aarch64-linux"
          - "x86_64-linux"
        package:
          - "server"
          - "client"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Nix store
        uses: actions/cache@v3.3.1
        id: nix-cache
        with:
          path: /tmp/nixcache
          key: ${{ runner.os }}-${{ hashFiles('**/flake.lock', '**/flake.nix') }}

      - name: Set up QEMU binfmt for building aarch64
        uses: docker/setup-qemu-action@v3

      - name: Install Nix
        uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011 # v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-platforms = aarch64-linux x86_64-linux

      - name: Import Nix store cache
        if: "steps.nix-cache.outputs.cache-hit == 'true'"
        run: |
          nix-store --import < /tmp/nixcache

      - name: Set up binary cache
        uses: cachix/cachix-action@v12
        with:
          name: nix-rust-template
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build package
        run: nix build --accept-flake-config .#packages.${{ matrix.system }}.${{ matrix.package }}

      - name: Export Nix store cache
        if: "steps.nix-cache.outputs.cache-hit != 'true'"
        run: |
          nix-store --export $(find /nix/store -maxdepth 1 -name '*-*') > /tmp/nixcache

  bundle:
    runs-on: ubuntu-latest
    needs:
      - build

    strategy:
      matrix:
        system:
          - "aarch64-linux"
          - "x86_64-linux"
        bundler:
          - name: "deb"
            extension: "deb"
          - name: "pacman"
            extension: "tar.xz"
          - name: "rpm"
            extension: "rpm"
        package:
          - "server"
          - "client"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Nix store
        uses: actions/cache@v3.3.1
        id: nix-cache
        with:
          path: /tmp/nixcache
          key: ${{ runner.os }}-${{ hashFiles('**/flake.lock', '**/flake.nix') }}

      - name: Set up QEMU binfmt for cross compiling
        uses: docker/setup-qemu-action@v3

      - name: Install Nix
        uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011 # v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-platforms = aarch64-linux x86_64-linux

      - name: Import Nix store cache
        if: "steps.nix-cache.outputs.cache-hit == 'true'"
        run: |
          nix-store --import < /tmp/nixcache

      - name: Set up binary cache
        uses: cachix/cachix-action@v12
        with:
          name: nix-rust-template
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build ${{ matrix.bundler.name }} package for ${{ matrix.system }}
        run: >-
          nix bundle
          --bundler .#${{ matrix.bundler.name }}
          --accept-flake-config
          --out-link "bundles/${{ github.event.repository.name }}-${{ matrix.system }}.${{ matrix.bundler.extension }}"
          .#packages.${{ matrix.system }}.${{ matrix.package }}

      - name: Export Nix store cache
        if: "steps.nix-cache.outputs.cache-hit != 'true'"
        run: |
          nix-store --export $(find /nix/store -maxdepth 1 -name '*-*') > /tmp/nixcache

      - name: Upload bundles
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.package }}-${{ matrix.bundler.name }}-${{ matrix.system }}
          path: bundles/*

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - bundle

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/**"
          commit: ${{ github.sha }}
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
